seed: 42
kfolds: 5
targets: [Deposited Thickness, Refractive Index, Wet Etch Rate]
features:
  - Deposition Temperature
  - Precursor Temperature
  - x-axis Location
  - y-axis Location
engineered_features:
  radial_r: true
  r2: true
  xy_interaction: true
  temps_interaction: true
  quad_terms: true
models:
  mlp:
    hidden_layer_sizes: [128, 64, 32]
    activation: relu
    alpha: 0.0005
    max_iter: 800
    early_stopping: true
  rf:
    n_estimators: 300
    max_depth: 10
    n_jobs: -1
bootstrap:
  n_models: 15
  sample_frac: 0.75
  replace: true
paths:
  dataset_candidates:
    - "./data/ald_dataset.xlsx"
    - "/mnt/c/Users/maana/Projects/Python/Data/Copy of 315^LN Dataset for trainingtesting.xlsx"
    - "C:/Users/maana/Projects/Python/Data/Copy of 315^LN Dataset for trainingtesting.xlsx"
  output_dir: "./outputs"

  #"C:\Users\maana\Projects\Python\Data\Copy of 315^LN Dataset for trainingtesting.xlsx"